
services:

  postgres:
    image: postgres
    container_name: postgresTestDb
    env_file: .env
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
